apiVersion: v1
kind: Service
metadata:
  name: node-react-service
  namespace: node-react
spec:
  type: NodePort
  selector:
    app: sample-node-react
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080